apps/user/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.urls import path, include
app_name='user'
from . import views
from apps.forum.views import indexMe
from django.views.generic import TemplateView
urlpatterns = [
  #path('',views.login_view,name='index'),
  path('',views.Person.as_view(),name='person'),
  path('author/',views.Author.as_view(),name='author'),
  path('<uuid:article_id>/',views.PersonDetaile.as_view(),name='author_detaile'),
  path('info/<uuid:article_id>/',views.InfoOthers.as_view(),name='info'),
  path('ProfileOthers/<uuid:article_id>/',views.ProfileOthers,name='ProfileOthers'),
  path('profile/', views.Profile,name='profile'),
  path('info/', views.Info, name='info'),
  path('forum/', indexMe, name='forum'),
  path('modify/', views.Modify.as_view(), name='modify'),
  path('retrieve/', views.Retrieve.as_view(), name='retrieve '),
  path('sing_email/', views.ResetUserView.as_view(), name='sing_email'),
  path('email_update/', views.EmailView.as_view(), name='email_update'),
  path('Guan/', views.Guan, name='Guan'),
  path('retrieveEmail/', views.RetrieveEmail.as_view(), name='retrieveEmail'),
  path('message/', views.message, name='message'),
  path('bindingQQ/', views.bindingQQ, name='bindingQQ'),
]

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from rest_framework.documentation import include_docs_urls

from rest_framework_jwt.views import obtain_jwt_token

from apps.article.views import ArticleCreated
from apps.course.views import CoursesList, CourseCreatedList, CourseListCreated, MeCoursesList
from apps.forum.views import Forum_plateView, ForumView, CommentView, Parent_CommentView
from apps.support.views import LinkList, EmailsList, BannerList, QQList, SeoList
from apps.user.views import test, captcha_refresh, yan, login_view, UserGetInfo, UserGetAllInfo, \
    PersonOthers, Register, active_user, get_message, UserMessages, qq, getClback, getClbackQQ
from django.views.generic import TemplateView

from website import settings
from apps.article import views
from apps.user.views import logout_view, Person, PersonApi,to_login
from rest_framework import routers

router = routers.DefaultRouter()
router.register('article_list', views.ArticleListView)
router.register('me_article_list', views.MeArticleListView)
router.register('ArticleCommit', views.ArticleCommit)
router.register('follow_list', views.FollowListView)
router.register('category', views.CategoryView)
router.register('article_Comment', views.ArticleCommintView)
router.register('comment_reply', views.ArticleCommentReplyView)
router.register('PersonApi', PersonApi)
router.register('apiinfo', UserGetInfo)
router.register('all_info', UserGetAllInfo)
# router.register('user_disbale', UserDisbale)
router.register('PersonOthers', PersonOthers)
router.register('UserMessages', UserMessages, base_name='UserMessages')
router.register('article', ArticleCreated)
router.register('courseList', CoursesList)
router.register('mecourseList', MeCoursesList)
router.register('course', CourseCreatedList)
router.register('Addtutorial', CourseListCreated)
router.register('BannerList', BannerList)
router.register('EmailsList', EmailsList)
router.register('LinkList', LinkList)
router.register('forum/category', Forum_plateView)
router.register('forum', ForumView)
router.register('CommentView', CommentView)
router.register('Parent_CommentView', Parent_CommentView)
router.register('get-list',QQList)
router.register('seo-list',SeoList,basename='seo-list')

urlpatterns = [

    #path('admins/', admin.site.urls),
    path('admin/', TemplateView.as_view(template_name='admin/index.html')),
   # path('404/', TemplateView.as_view(template_name='500.html')),
    # path('',test), # 这是生成验证码的图片
    url(r'^captcha/', include('captcha.urls')),
    path('refresh/', captcha_refresh),  # 这是生成验证码的图片
    path('yan/', yan),  # 这是生成验证码的图片
    path('', views.Home, name='home'),
    path('54', views.test, name='54'),
    path('login/', login_view, name='index'),
    path('info/', get_message, name='info'),
    path('person/', include('apps.user.urls')),
    path('logou/', logout_view, name='logou'),
    path('register/', Register.as_view(), name='register'),
    path('article/', include('apps.article.urls')),
    path('course/', include('apps.course.urls')),
    path('support/', include('apps.support.urls')),
    path('forum/', include('apps.forum.urls')),
    path('ads.txt/',TemplateView.as_view(template_name='ads.txt')),
    #url(r'^activate/(?P<token>\w+.[-_\w]*\w+.[-_\w]*\w+)/$', active_user, name='active_user'),
    path('activate/<str:token>', active_user, name='active_user'),
    url(r'^search/', include('haystack.urls'), name='haystack_search'),

    re_path(r'^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("api-docs/", include_docs_urls("API文档")),
    re_path(r'api/login/$', obtain_jwt_token),  # jwt认证
    url('auth-qq', to_login, name='qq-login'),
    url('qq', qq, name='qq'),
    url('callbackget', getClback, name='callbackget'),
    url('getClbackQQ', getClbackQQ, name='getClbackQQ'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})  # 配置文件上传html显示
]

#全局404
handler404='apps.user.views.page_not_found'
handler500='apps.user.views.page_error'

apps/article/models.py
import uuid
from datetime import datetime


from django.db import models

from apps.user.models import User
# Create your models here.


class Category_Article(models.Model):
    """
    分类
    """
    name = models.CharField(max_length=100)
    add_time = models.DateTimeField(default=datetime.now)
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name


class Article(models.Model):
    """文章"""
    id = models.UUIDField(default=uuid.uuid4,primary_key=True)
    authors = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户')
    category = models.ForeignKey(Category_Article,on_delete=models.CASCADE,verbose_name='分类')
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=200,blank=True,null=True)
    desc = models.CharField(max_length=256,blank=True,null=True)
    list_pic = models.ImageField(upload_to='article/%Y%m%d',blank=True,null=True)
    content = models.TextField()
    click_nums = models.IntegerField(default=0,verbose_name='阅读数量')
    is_show = models.BooleanField(default=True,verbose_name='是否删除')
    add_time = models.DateTimeField(auto_now_add=True)

    def get_number(self):
        n= self.article_comment_set.all()
        num = self.article_comment_set.count()
        for i in n:
            num+=i.articlecommentreply_set.count()
        return num

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ('-add_time',)


class Recommend(models.Model):
    recommends = models.ForeignKey(Article,on_delete=models.CASCADE,null=True,)
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    add_time = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = '文章推荐'
        verbose_name_plural = verbose_name
        ordering = ('-add_time',)


class Article_Comment(models.Model):
    """"评论"""
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户')
    article =models.ForeignKey(Article,verbose_name='文章',on_delete=models.CASCADE)
    comments = models.TextField(verbose_name='评论')
    address = models.CharField(max_length=50,verbose_name='地址',blank=True,null=True)
    url = models.CharField(max_length=60, blank=True, null=True, default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.article.title

    class Meta:
        verbose_name ='文章评论'
        verbose_name_plural=verbose_name
        ordering = ('-add_time',)



class ArticleCommentReply(models.Model):
    """评论回复"""
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='当前用户',related_name='form_uid')
    to_uids = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='目标用户',related_name='to_uids',default='')
    comments = models.TextField(verbose_name='回复内容')
    url = models.CharField(max_length=60,blank=True,null=True,default='')
    aomments_id = models.ForeignKey(Article_Comment,on_delete=models.CASCADE,verbose_name='回复id')
    address = models.CharField(max_length=50, verbose_name='地址',blank=True,null=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')


class Headlines(models.Model):
    """头条"""
    id = models.UUIDField(default=uuid.uuid4,primary_key=True)
    title = models.CharField(max_length=200,verbose_name='标题')
    category = models.CharField(max_length=20,verbose_name='分类')
    conent = models.TextField(verbose_name='内容',default='')
    author_name = models.CharField(max_length=100,verbose_name='来源')
    url = models.URLField(verbose_name='地址')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        ordering = ('-add_time',)

templates/pc/person/infoOthers.html
{% extends 'pc/person/indexOthers.html' %}
{% load static %}

{% block end %}
    <div class="person fl">

        <div class="clearfix">
            <div class="fl left_nav">
                <ul id="info">
                    <li data-type="" class="active"><a href="javascript:;">个人资料</a></li>
                </ul>
            </div>
            <article class="fr">
                 <div class="blogs">
                     <div class="blogs_head" style="background: url({% static 'img/recommend.png' %})no-repeat 0 50%;">
                         <span>个人资料</span>
                     </div>
                     <div class="follow_main">
                         <div class="info_item clearfix"style="position: relative">
                             <label for="name">头像</label>
                             <a class="imgbox">
                                 <span id="img3" class="info_img" style="background-image:url({% if user.user_imag  %}
                                 {{ MEDIA_URL }}{{user.user_imag }}
                                     {% elif user.user_image%}
                                     {{user.user_image }}
                                     {% else %}
                                     {% static 'img/pc-icon.png' %}
                                 {% endif %});"></span>
                              </a>
                         </div>
                         <div class="info_item clearfix">
                             <label for="name">用户名</label>
                             <input type="text" name="username"class="val origin" value="{{ user.username }}" disabled>
                         </div>
                         <div class="info_item clearfix">
                             <label for="name">职位</label>
                                 <input type="text" name="position"class="val origin" value="{{ user.position }}"disabled>
                             </div>
                         <div class="info_item clearfix">
                             <label for="name" style="left:-7px;position: relative;">个人介绍 </label>
                             <textarea name="info" id="me" class="val origin"  disabled>{{ user.info }}</textarea>
                             </div>

                     </div>
                 </div>
            </article>
        </div>
    </div>

{% endblock %}
{% block js %}
     <script src="{% static 'js/promise.min.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script>
     function flollw (obj){
          $.ajax({
                url:'/person/author/',
                type:'post',
                data:{follow:obj,'username':'{{ request.user.id }}'},
                  headers:{'X-CSRFToken':$.cookie('csrftoken')},
                success:function (data) {
                        if(data.status==403){
                       swal({
                          text: data.message,
                          icon: "error",
                        }).then(function () {
                           window.location.href = "{% url 'index' %}?next={{ request.path }}"
                       })
                    }else{
                    swal({
                          text: data.message,
                          icon: "success",
                        }).then(function () {
                            window.location.reload()
                        })
                     }
                },
                error:function (xhr) {
                    console.log(xhr)
                }
            })
    }
    </script>
{% endblock %}

templates/pc/person/profile.html
{% extends 'pc/person/index.html' %}
{% load static %}
{% block end %}
    <div class="person fl">

        <div class="clearfix">
            <div class="fl left_nav">
                <ul id="follow">
                    <li data-type="" class="active"><a href="javascript:;">关注</a></li>
                    <li data-type="" class=""><a href="javascript:;">粉丝</a></li>

                </ul>
            </div>
            <article class="fr">
                 <div class="blogs">
                     <div class="blogs_head" style="background: url({% static 'img/recommend.png' %})no-repeat 0 50%;">我的关注</div>
                     <div class="follow_main">
                         <ul class="clearfix">

                             {% for foo in count %}
                                    <li class="follow_item">
                                 <dl class="clearfix">
                                     <dt class="fl">
                                         <a target="_blank" title="" href="{% url 'user:author_detaile' foo.id %}">
                                            <img class="follow_item_img" width="50" height="50"style="background-color: #ccc;" alt="" src="{% if foo.user_imag %}
                                            {{ MEDIA_URL }}{{ foo.user_imag }}
                                            {% elif foo.user_image %}
                                            {{ foo.user_image }}
                                            {% else %}
                                            {% static 'img/pc-icon.png' %}
                                            {% endif %}">
                                         </a>
                                     </dt>
                                     <dd class="fl">
                                         <div class="follow_item_name">
                                            <a target="_blank" title="" alt="" href="{% url 'user:author_detaile' foo.id %}">{{ foo.username }}</a>
                                         </div>
                                         <div class="follow_item_info"style="text-align: left">
                                             <p>文章:{{ foo.article_set.count }}</p>
                                             <p>帖子:{{ foo.forum_set.count }}</p>
                                         </div>
                                     </dd>
{#                                     <dd class="fl follow_num">#}
{#                                         <div class="">#}
{#                                             <div>关注</div>#}
{#                                             <div>{{ floow.count }}</div>#}
{#                                         </div>#}
{#                                     </dd>#}
{#                                     <dd class="fl fans_num">#}
{#                                         <div class="">#}
{#                                             <div>粉丝</div>#}
{#                                             <div>{{ floow.count }}</div>#}
{#                                         </div>#}
{#                                     </dd>#}
                                     <dd class="fr follow_btn">
                                         <a href="javascript:;" type_id="{{ foo.id }}" class="guan">取消关注</a>
                                     </dd>
                                 </dl>
                             </li>
                             {% endfor %}
                         </ul>
                     </div>
                    <div class="follow_main" style="display: none">
                         <ul class="clearfix">
                             {% for foo in floow %}
                                    <li class="follow_item">
                                 <dl class="clearfix">
                                     <dt class="fl">
                                         <a target="_blank" title="" href="{% url 'user:author_detaile' foo.id %}">
                                            <img class="follow_item_img" width="50" height="50" alt="" style="" src="{% if foo.user_imag %}
                                            {{ MEDIA_URL }}{{ foo.user_imag }}
                                            {% elif foo.user_image %}
                                            {{ foo.user_image}}
                                            {% else %}
                                            {% static 'img/pc-icon.png' %}
                                            {% endif %}">
                                         </a>
                                     </dt>
                                     <dd class="fl">
                                         <div class="follow_item_name">
                                            <a target="_blank" title="" alt="" href="{% url 'user:author_detaile' foo.id %}">{{ foo.username }}</a>
                                         </div>
                                         <div class="follow_item_info"style="text-align: left">
                                            <p>文章:{{ foo.article_set.count }}</p>
                                             <p>帖子:{{ foo.forum_set.count }}</p>
                                         </div>
                                     </dd>

                                 </dl>
                             </li>
                             {% endfor %}
                         </ul>
                     </div>
                 </div>
            </article>
        </div>
    </div>
{% comment %} <aside class="fr">


        <div class="aside_pubnum">
            <div class="flex_justify">
               <div class="aside_my_div">
                   <p><img src="img/public.png" alt=""></p>
                   <p>写文章</p>
               </div>
                <div class="aside_my_div">
                    <p><img src="img/public.png" alt=""></p>
                    <p>提问</p>
                </div>
            </div>
        </div>
        <div class="aside_visit">
            <div>
                <div class="blogs_head" style="background: url(img/recommend.png)no-repeat 0 50%;">访客</div>
                <div>
                    <div class="visit_item">
                         <div class="visit_head img_cover"></div>
                        <div class="visit_info_text">
                            <p>狙击手</p>
                            <p class="vi_co">48分钟前</p>
                        </div>
                    </div>
                     <div class="visit_item">
                         <div class="visit_head img_cover"></div>
                        <div class="visit_info_text">
                            <p>狙击手</p>
                            <p class="vi_co">48分钟前</p>
                        </div>
                    </div>
                     <div class="visit_item">
                         <div class="visit_head img_cover"></div>
                        <div class="visit_info_text">
                            <p>狙击手</p>
                            <p class="vi_co">48分钟前</p>
                        </div>
                    </div>
                     <div class="visit_item">
                         <div class="visit_head img_cover"></div>
                        <div class="visit_info_text">
                            <p>狙击手</p>
                            <p class="vi_co">48分钟前</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </aside>{% endcomment %}
{% endblock %}
{% block js %}
    <script src="{% static 'js/promise.min.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script>
    $(function () {
        $('.guan').on('click',function () {
            var n = $(this).attr('type_id')
            var self = $(this)
             $.ajax({
                url:"/person/Guan/",
                type:'POST',
                data:{follow:n,user:'{{ request.user.id }}'},
                success:function (data) {
                    if(data.data==200){
                          swal({
                              text: "已取消!",
                              icon: "success",
                            }).then(function () {
                               self.parents('li').remove()
                           })
                    }else {
                          swal({
                              text: "取消失败,稍后重试!",
                              icon: "error",
                            })
                    }



                }
            })
        })
        $('#follow li').on('click',function () {
               $('.follow_main').siblings('.blogs_head').text('我的'+$(this).text())
            $(this).addClass('active').siblings().removeClass('active')
            var index= $(this).index()
            $('.follow_main').eq(index).show().siblings('.follow_main').hide()
        })

    })
    </script>
{% endblock %}

templates/pc/person/profileOthers.html
{% extends 'pc/person/indexOthers.html' %}
{% load static %}
{% block end %}
    <div class="person fl">

        <div class="clearfix">
            <div class="fl left_nav">
                <ul id="follow">
                    <li data-type="" class="active"><a href="javascript:;">关注</a></li>
                    <li data-type="" class=""><a href="javascript:;">粉丝</a></li>

                </ul>
            </div>
            <article class="fr">
                 <div class="blogs">
                     <div class="blogs_head" style="background: url({% static 'img/recommend.png' %})no-repeat 0 50%;">他的关注</div>
                     <div class="follow_main">
                         <ul class="clearfix">

                             {% for foo in count %}
                                    <li class="follow_item">
                                 <dl class="clearfix">
                                     <dt class="fl">
                                         <a target="_blank" title="" href="{% url 'user:author_detaile' foo.id %}">
                                            <img class="follow_item_img" style="background-color: #ccc;" width="50" height="50" alt="" src="{% if foo.user_imag %}
                                            {{ MEDIA_URL }}{{ foo.user_imag }}
                                            {% elif  foo.user_image  %}
                                            {{ foo.user_image }}
                                            {% else %}
                                            {% static 'img/pc-icon.png' %}
                                            {% endif %}">
                                         </a>
                                     </dt>
                                     <dd class="fl">
                                         <div class="follow_item_name">
                                            <a target="_blank" title="" alt="" href="{% url 'user:author_detaile' foo.id %}">{{ foo.username }}</a>
                                         </div>
                                         <div class="follow_item_info">
                                            <p>文章:{{ foo.article_set.count }}</p>
                                             <p>帖子:{{ foo.forum_set.count }}</p>
                                         </div>
                                     </dd>

                                 </dl>
                             </li>
                             {% endfor %}
                         </ul>
                     </div>
                    <div class="follow_main" style="display: none">
                         <ul class="clearfix">
                             {% for foo in floow %}
                                    <li class="follow_item">
                                 <dl class="clearfix">
                                     <dt class="fl">
                                         <a target="_blank" title="" href="{% url 'user:author_detaile' foo.id %}">
                                            <img class="follow_item_img" width="50" height="50" style="background-color: #ccc;" alt="" src="{% if foo.user_imag %}
                                            {{ MEDIA_URL }}{{ foo.user_imag }}
                                            {% elif foo.user_image  %}
                                            {{ foo.user_image }}
                                            {% else %}
                                            {% static 'img/pc-icon.png' %}
                                            {% endif %}">
                                         </a>
                                     </dt>
                                     <dd class="fl">
                                         <div class="follow_item_name">
                                            <a target="_blank" title="" alt="" href="{% url 'user:author_detaile' foo.id %}">{{ foo.username }}</a>
                                         </div>
                                         <div class="follow_item_info">
                                             <p>文章:{{ foo.article_set.count }}</p>
                                             <p>帖子:{{ foo.forum_set.count }}</p>
                                         </div>
                                     </dd>

                                 </dl>
                             </li>
                             {% endfor %}
                         </ul>
                     </div>
                 </div>
            </article>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script src="{% static 'js/promise.min.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script>
    function flollw (obj){
          $.ajax({
                url:'/person/author/',
                type:'post',
                data:{follow:obj,'username':'{{ request.user.id }}'},
                  headers:{'X-CSRFToken':$.cookie('csrftoken')},
                success:function (data) {
                       if(data.status==403){
                       swal({
                          text: data.message,
                          icon: "error",
                        }).then(function () {
                           window.location.href = "{% url 'index' %}?next={{ request.path }}"
                       })
                    }else{
                    swal({
                          text: data.message,
                          icon: "success",
                        }).then(function () {
                            window.location.reload()
                        })
                     }
                },
                error:function (xhr) {
                    console.log(xhr)
                }
            })
    }
    $(function () {

        $('#follow li').on('click',function () {
             $('.follow_main').siblings('.blogs_head').text('他的'+$(this).text())
            $(this).addClass('active').siblings().removeClass('active')
            var index= $(this).index()
            $('.follow_main').eq(index).show().siblings('.follow_main').hide()
        })

    })
    </script>
{% endblock %}