apps/article/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
from django.conf.urls import url
from django.urls import path, include
app_name='article'
from . import views
urlpatterns = [

  path('created/',views.Article_Add,name='created'),

  path('',views.ArticleList,name='index'),
  path('me/',views.ArticleMe,name='me'),
  path('blog_img_upload/',views.blog_img_upload,name='blog_img_upload'),
  path('detail/<uuid:article_id>',views.Article_detail,name='detail'),
  path('update/<uuid:article_id>',views.ArticleUpdate,name='update'),
  path('update_image/<uuid:article_id>',views.RemoveImage,name='update_image'),
  path('delete/',views.ArticleDelete,name='delete'),
  path('api/',views.api,name='api'),
  path('apis/',views.addModel),

]

apps/course/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
from django.conf.urls import url
from django.urls import path, include
app_name='course'
from . import views
urlpatterns = [

  path('',views.List,name='index'),

  path('<uuid:course_id>/<str:list_id>.html/',views.Detail,name='detail'),


  path('api/<uuid:courses_id>/',views.courseViewApi,name='courseViewApi'),

]

apps/forum/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.urls import path, include
app_name='forum'
from . import views

urlpatterns = [
  #path('',views.login_view,name='index'),
  path('',views.index,name='forum'),
  path('add/',views.add_forum,name='add'),
  path('detail/<uuid:forum_id>/',views.forum_detail,name='detail'),
  path('cagetory/<int:category>/',views.forum_category,name='id'),
  path('del/<uuid:id>/',views.delForum,name='del'),
  ]

apps/support/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.urls import path, include
app_name='support'
from . import views
urlpatterns = [
  #path('',views.login_view,name='index'),
  path('',views.index,name='support'),

]

apps/user/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.urls import path, include
app_name='user'
from . import views
from apps.forum.views import indexMe
from django.views.generic import TemplateView
urlpatterns = [
  #path('',views.login_view,name='index'),
  path('',views.Person.as_view(),name='person'),
  path('author/',views.Author.as_view(),name='author'),
  path('<uuid:article_id>/',views.PersonDetaile.as_view(),name='author_detaile'),
  path('info/<uuid:article_id>/',views.InfoOthers.as_view(),name='info'),
  path('ProfileOthers/<uuid:article_id>/',views.ProfileOthers,name='ProfileOthers'),
  path('profile/', views.Profile,name='profile'),
  path('info/', views.Info, name='info'),
  path('forum/', indexMe, name='forum'),
  path('modify/', views.Modify.as_view(), name='modify'),
  path('retrieve/', views.Retrieve.as_view(), name='retrieve '),
  path('sing_email/', views.ResetUserView.as_view(), name='sing_email'),
  path('email_update/', views.EmailView.as_view(), name='email_update'),
  path('Guan/', views.Guan, name='Guan'),
  path('retrieveEmail/', views.RetrieveEmail.as_view(), name='retrieveEmail'),
  path('message/', views.message, name='message'),
  path('bindingQQ/', views.bindingQQ, name='bindingQQ'),
]

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from rest_framework.documentation import include_docs_urls

from rest_framework_jwt.views import obtain_jwt_token

from apps.article.views import ArticleCreated
from apps.course.views import CoursesList, CourseCreatedList, CourseListCreated, MeCoursesList
from apps.forum.views import Forum_plateView, ForumView, CommentView, Parent_CommentView
from apps.support.views import LinkList, EmailsList, BannerList, QQList, SeoList
from apps.user.views import test, captcha_refresh, yan, login_view, UserGetInfo, UserGetAllInfo, \
    PersonOthers, Register, active_user, get_message, UserMessages, qq, getClback, getClbackQQ
from django.views.generic import TemplateView

from website import settings
from apps.article import views
from apps.user.views import logout_view, Person, PersonApi,to_login
from rest_framework import routers

router = routers.DefaultRouter()
router.register('article_list', views.ArticleListView)
router.register('me_article_list', views.MeArticleListView)
router.register('ArticleCommit', views.ArticleCommit)
router.register('follow_list', views.FollowListView)
router.register('category', views.CategoryView)
router.register('article_Comment', views.ArticleCommintView)
router.register('comment_reply', views.ArticleCommentReplyView)
router.register('PersonApi', PersonApi)
router.register('apiinfo', UserGetInfo)
router.register('all_info', UserGetAllInfo)
# router.register('user_disbale', UserDisbale)
router.register('PersonOthers', PersonOthers)
router.register('UserMessages', UserMessages, base_name='UserMessages')
router.register('article', ArticleCreated)
router.register('courseList', CoursesList)
router.register('mecourseList', MeCoursesList)
router.register('course', CourseCreatedList)
router.register('Addtutorial', CourseListCreated)
router.register('BannerList', BannerList)
router.register('EmailsList', EmailsList)
router.register('LinkList', LinkList)
router.register('forum/category', Forum_plateView)
router.register('forum', ForumView)
router.register('CommentView', CommentView)
router.register('Parent_CommentView', Parent_CommentView)
router.register('get-list',QQList)
router.register('seo-list',SeoList,basename='seo-list')

urlpatterns = [

    #path('admins/', admin.site.urls),
    path('admin/', TemplateView.as_view(template_name='admin/index.html')),
   # path('404/', TemplateView.as_view(template_name='500.html')),
    # path('',test), # 这是生成验证码的图片
    url(r'^captcha/', include('captcha.urls')),
    path('refresh/', captcha_refresh),  # 这是生成验证码的图片
    path('yan/', yan),  # 这是生成验证码的图片
    path('', views.Home, name='home'),
    path('54', views.test, name='54'),
    path('login/', login_view, name='index'),
    path('info/', get_message, name='info'),
    path('person/', include('apps.user.urls')),
    path('logou/', logout_view, name='logou'),
    path('register/', Register.as_view(), name='register'),
    path('article/', include('apps.article.urls')),
    path('course/', include('apps.course.urls')),
    path('support/', include('apps.support.urls')),
    path('forum/', include('apps.forum.urls')),
    path('ads.txt/',TemplateView.as_view(template_name='ads.txt')),
    #url(r'^activate/(?P<token>\w+.[-_\w]*\w+.[-_\w]*\w+)/$', active_user, name='active_user'),
    path('activate/<str:token>', active_user, name='active_user'),
    url(r'^search/', include('haystack.urls'), name='haystack_search'),

    re_path(r'^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("api-docs/", include_docs_urls("API文档")),
    re_path(r'api/login/$', obtain_jwt_token),  # jwt认证
    url('auth-qq', to_login, name='qq-login'),
    url('qq', qq, name='qq'),
    url('callbackget', getClback, name='callbackget'),
    url('getClbackQQ', getClbackQQ, name='getClbackQQ'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})  # 配置文件上传html显示
]

#全局404
handler404='apps.user.views.page_not_found'
handler500='apps.user.views.page_error'

apps/support/models.py
from django.db import models

# Create your models here.


class Banners(models.Model):
    """
    广告
    """
    title = models.CharField(max_length=100,blank=True,null=True)
    image = models.ImageField(upload_to='support/%Y%m%d',blank=True,null=True)
    url = models.URLField(blank=True,null=True)
    add_time = models.DateTimeField(auto_now_add=True)


class Emails(models.Model):
    """联系方式"""
    qq = models.CharField(max_length=11,blank=True,null=True)
    iphone = models.CharField(max_length=11,blank=True,null=True)
    email = models.EmailField(blank=True,null=True)
    add_time = models.DateTimeField(auto_now_add=True)


class link(models.Model):
    """友情链接"""
    title =  models.CharField(max_length=100)
    url = models.URLField()
    add_time = models.DateTimeField(auto_now_add=True)


class QQ(models.Model):
    """交流群"""
    title =  models.CharField(max_length=100)
    qq = models.IntegerField()
    is_active = models.BooleanField(default=False)


class Seo(models.Model):
    """SEO"""
    name = models.CharField(max_length=100,default='')
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=20)
    desc = models.TextField()
    keywords = models.TextField()

apps/article/forms.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
from django import forms

from apps.article.models import Article


class Article_form(forms.ModelForm):
    category = forms.IntegerField(required=True)
    class Meta:
        model = Article
        fields = ['title','authors','content']

apps/forum/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from django.core.cache import cache
from django.core.paginator import PageNotAnInteger
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.http import JsonResponse
from django.shortcuts import render, reverse, redirect, get_object_or_404

# Create your views here.
from django_filters.rest_framework import DjangoFilterBackend
from pure_pagination import Paginator
from rest_framework import mixins, viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

from apps.article.views import StandardResultsSetPagination
from apps.forum.filter import ForumFilter
from apps.forum.forms import Forum_form, ParentComment
from apps.forum.models import Forum_plate, Forum, Comment, Parent_Comment
from apps.forum.serializers import Forum_plateSerializers, ForumSerializers, CommentSerializers, \
    Pernents_CommentSerializers
from apps.support.models import Seo
from apps.uitls.permissions import IsOwnerOr, IsOwnerOrReadOnly
from apps.user.models import UserMessage, User


# def get_online_count():
#     online_ips = cache.get("online_ips", [])
#     print(online_ips)
#     if online_ips:
#         #online_ips = cache.get_many(online_ips).keys()
#         return len(online_ips)
#     return 0


def index(request):
    """
    帖子首页
    :param request:
    :return:
    """
    seo_list = get_object_or_404(Seo, name='社区论坛')
    plate = Forum_plate.objects.all()
    forum = Forum.objects.filter(hidden=False)
    job = Forum.objects.filter(category__name='求职招聘')
    try:
        page = request.GET.get('page', 1)
        if page == '':
            page = 1
    except PageNotAnInteger:
        page = 1
        # Provide Paginator with the request object for complete querystring generation
    p = Paginator(forum, 10, request=request)
    people = p.page(page)
    return render(request,'pc/forum.html',locals())



@login_required(login_url='/login')
def indexMe(request):
    """
    wd帖子首页
    :param request:
    :return:
    """
    plate = Forum_plate.objects.all()
    forum = Forum.objects.filter(hidden=False)
    count = User.objects.filter(follow__fan__id=request.user.id)
    floow = User.objects.filter(fan__follow_id=request.user.id)
    try:
        page = request.GET.get('page', 1)
        if page == '':
            page = 1
    except PageNotAnInteger:
        page = 1
        # Provide Paginator with the request object for complete querystring generation
    p = Paginator(forum, 10, request=request)
    people = p.page(page)
    return render(request,'pc/forum_me.html',locals())

@login_required(login_url='/login')
def add_forum(request):
    """
    新增帖子
    :param request:
    :return:
    """
    category = Forum_plate.objects.all()
    if request.method == 'POST':
        form = Forum_form(request.POST)
        if form.is_valid():
            forum = Forum()
            forum.title = form.cleaned_data.get('title')
            forum.category_id = form.cleaned_data.get('category')
            forum.keywords = form.cleaned_data.get('keywords')
            forum.content = form.cleaned_data.get('content')
            forum.authors = form.cleaned_data.get('authors')
            try:
                forum.save()
                return JsonResponse({"code": 200, "data": "发布成功"})
            except Exception:
                return JsonResponse({"code": 400, "data": "发布失败"})
    return render(request,'pc/forum_add.html',locals())

@login_required(login_url='/login')
def delForum(request,id):
    """
    删除帖子
    :param request:
    :param id:
    :return:
    """
    if request.is_ajax():
        try:
            data = get_object_or_404(Forum,pk=id)
            data.hidden=True
            data.save()
            return JsonResponse({'status':200,'message':'删除成功'})
        except Exception as e:
            return JsonResponse({'status': 400, 'message': '删除失败'})


def forum_category(request,category):
    """
    分类
    :param request:
    :param category:
    :return:
    """
    cate_list = Forum.objects.filter(category_id=category,hidden=False)
    plate = Forum_plate.objects.all()

    job = Forum.objects.filter(category__name='求职招聘')
    type = get_object_or_404(Forum_plate,pk=category)
    try:
        page = request.GET.get('page', 1)
        if page == '':
            page = 1
    except PageNotAnInteger:
        page = 1
        # Provide Paginator with the request object for complete querystring generation
    p = Paginator(cate_list, 20, request=request)
    people = p.page(page)

    return render(request,'pc/forum_category.html',locals())


def forum_detail(request,forum_id):
    """
    详情
    :param request:
    :param forum_id:
    :return:
    """
    dicts = get_object_or_404(Forum,pk=forum_id)
    dicts.click_nums+=1
    dicts.save()
    if request.method == 'POST':
        forms = ParentComment(request.POST)
        if forms.is_valid():
            try:
                data = Parent_Comment()
                data.forums = forms.cleaned_data.get('forums')
                data.user = forms.cleaned_data.get('user')
                data.comments = forms.cleaned_data.get('comments')
                data.parent_comments = forms.cleaned_data.get('parent_comments')
                data.to_Parent_Comments = forms.cleaned_data.get('to_Parent_Comments')
                data.url = forms.cleaned_data.get('url')
                data.address = request.POST.get('address')
                data.save()
                return JsonResponse({"code": 200, "data": "发布成功"})
            except Exception as e:
                return JsonResponse({"code": 400, "data": "发布失败"})
    return render(request,'pc/forum_detail.html',{'dicts':dicts})


@receiver(post_save, sender=Parent_Comment)
def my_callback_reply(sender, **kwargs):
    """
    评论通知
    :param sender:
    :param kwargs:
    :return:
    """
    try:
        message = UserMessage()
        message.user_id = kwargs['instance'].to_Parent_Comments_id
        message.ids = kwargs['instance'].forums_id
        message.to_user_id = kwargs['instance'].user.id
        message.has_read = False
        message.url =kwargs['instance'].url
        message.message = "你参与的 %s 帖子评论有人回复了,快去看看吧!"%kwargs['instance'].parent_comments.forums.title
        message.save()
    except Exception as e:
        pass






class Forum_plateView(mixins.UpdateModelMixin,mixins.CreateModelMixin,viewsets.ReadOnlyModelViewSet):
    """TODO 版块分類"""
    queryset = Forum_plate.objects.all()
    serializer_class = Forum_plateSerializers
    permission_classes = (IsAuthenticated, IsOwnerOr)  # 未登录禁止访问
    authentication_classes = [SessionAuthentication, JSONWebTokenAuthentication]


class ForumView(viewsets.ModelViewSet):
    """TODO 帖子"""
    queryset = Forum.objects.filter(hidden=False)
    serializer_class = ForumSerializers
    pagination_class = StandardResultsSetPagination
    permission_classes = (IsAuthenticated, IsOwnerOr)  # 未登录禁止访问
    filter_backends = (DjangoFilterBackend,)
    filter_class = ForumFilter
    authentication_classes = [SessionAuthentication, JSONWebTokenAuthentication]

    def get_queryset(self):
        if self.request.user.is_superuser and self.request.user:
            return Forum.objects.filter(hidden=False)
        else:
            return Forum.objects.filter(authors=self.request.user)



class CommentView(viewsets.ModelViewSet):
    """TODO 评论"""
    queryset = Comment.objects.all()
    serializer_class = CommentSerializers
    permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)  # 未登录禁止访问
    authentication_classes = [SessionAuthentication, JSONWebTokenAuthentication]


@receiver(post_save, sender=Comment)
def my_callback(sender, **kwargs):
    """
    评论通知
    :param sender:
    :param kwargs:
    :return:
    """
    message = UserMessage()
    message.user=kwargs['instance'].forums.authors
    message.ids = kwargs['instance'].forums.id
    message.to_user_id = kwargs['instance'].user_id
    message.has_read = False
    message.url =kwargs['instance'].url
    message.message="你的%s帖子被人评论了,快去看看吧!"%kwargs['instance'].forums.title
    message.save()




class Parent_CommentView(viewsets.ModelViewSet):
    """TODO 评论回复"""
    queryset = Parent_Comment.objects.all()
    serializer_class = Pernents_CommentSerializers
    permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)  # 未登录禁止访问
    authentication_classes = [SessionAuthentication, JSONWebTokenAuthentication]

templates/pc/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
    <meta name="sogou_site_verification" content="KyUYfNQHr5"/>
    <meta name="360-site-verification" content="809891f94b37ddaef0edde649234de9e" />
    <meta name="baidu-site-verification" content="ERi24bXcVX" />
    <meta name="msvalidate.01" content="E02DAEAC571668CD032A487D5EFF5F01" />
    <meta name="keywords" content="{% block keywords %}
    {% endblock %}">
    <meta name="description" content="{% block desc %}
    {% endblock %}">
    <meta name="author" content="{% block authors %}
    {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/public.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <style>
        #cnzz_stat_icon_1277918196{
        position: absolute;
        bottom: 15px;
        z-index: 1;
            margin-bottom: 0;
        }
    </style>
    {% block css %}{% endblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.min.js' %}"></script>
    <script src="{% static 'js/public.js' %}"></script>
    <script src="{% static 'js/xss.js' %}"></script>
    {% block link_js %}
    {% endblock %}
{% comment %}<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
(adsbygoogle = window.adsbygoogle || []).push({
google_ad_client: "pub-1595090025336102",
enable_page_level_ads: true
});
</script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-1595090025336102",
          enable_page_level_ads: true
     });
</script>{% endcomment %}
<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?5e7e3927360d6aa3d7683f40212d4369";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
</script>

<script>
(function(){
var src = (document.location.protocol == "http:") ? "http://js.passport.qihucdn.com/11.0.1.js?7d553af6cd362b8ae466889542d8651f":"https://jspassport.ssl.qhimg.com/11.0.1.js?7d553af6cd362b8ae466889542d8651f";
document.write('<script src="' + src + '" id="sozz"><\/script>');
})();
</script>
{% comment %}<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" : "http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1277918196'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1277918196%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>{% endcomment %}
</head>
<body>
<header>
    <div class="main clearfix">
        <a class="fl logo" href="{% url 'home' %}" style="height:45px;background: url({% static 'img/logo.png' %})no-repeat;width: 120px;background-size: 120px 45px;
    margin-top: 7px;">
            {% comment %}<img style="width: 40px;margin-top: 20px;" src="{% static 'img/logo.png' %}" alt="">{% endcomment %}
        </a>
        <nav class="fl">
            <ul class="clearfix headers_nav">
                <li class="fl"><a class="{% if request.path == '/' %}
                active
                {% endif %}" href="{% url 'home' %}">首页</a></li>
                <li class="fl"><a class=" {% if request.path|slice:'9' == '/article/' %}
                active
                {% endif %}"href="{% url 'article:index' %}">文章</a></li>

                <li class="fl"><a class=" {% if request.path|slice:'8' == '/course/' %}
                active
                {% endif %} "href="{% url 'course:index' %}">教程</a></li>
             <li class="fl"><a class=" {% if request.path|slice:'7' == '/forum/' %}
                active
                {% endif %}" href="{% url 'forum:forum' %}">社区论坛</a></li>
                <li class="fl"><a class=" {% if request.path|slice:'9' == '/support/' %}
                active
                {% endif %}" href="{% url 'support:support' %}">支持与赞助</a></li>
            </ul>
        </nav>
        <div class="fr user">
            <ul class="clearfix"style="display:flex;display: -webkit-flex;">
            <li>
                <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                  <input type="text" name="q" placeholder="搜索" required class="form_control">
{#                  <button type="submit">#}
                      <button type="submit" class="form_search"></button>
{#                  </button>#}
                </form>
            </li>
                <li class="fl style" style="background: url({% static 'img/public.png' %})no-repeat 0 50%;"><a href="{% url 'article:created' %}">写文章</a></li>
                <li class="fl style" style="background: url({% static 'img/phone.png' %})no-repeat 0 50%;"><a href="">手机阅读</a></li>
                {% if request.user.is_authenticated %}
                    <li class="fl avatar">
                        <a class="img_cover" style="background: url({% if request.user.user_imag %}
                            {{ MEDIA_URL }}{{ request.user.user_imag  }}
                            {% elif request.user.user_image %}
                            {{ request.user.user_image }}
                            {% else %}
                            {% static 'img/pc-icon.png' %}
                        {% endif %})no-repeat;">
                        <b id="yuan" style="width: 10px;height: 10px;
                        position: absolute;
                        display: none;
                        right: 0;
                        background: red;-webkit-border-radius: 50%;-moz-border-radius: 50%;border-radius: 50%;"></b>
                        </a>
                        <ul class="meau meau_hide">
                            <li><a href="{% url 'user:person' %}">个人中心</a></li>
                         <li><a href="{% url 'user:message' %}">消息<span class="badge"></span></a></li>
                            {% if user.is_staff  %}
                                <li><a href="/admin">系统管理</a></li>
                            {% endif %}
                            <li><a href="{% url 'logou' %}">退出</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="fl"><a href="/login">登录 </a> | <a href="{% url 'register' %}"> 注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>
{% block content %}

{% endblock %}

<footer class="footer">
    <p class="main">Powered by
        <a>爱上她的歌</a>
        <a href="http://www.miitbeian.gov.cn" target="_blank">蜀ICP备18023241号-1</a>
    </p>
</footer>
 <a href="javascript:;" id="toTop" class=" fa fa-chevron-up"></a>
<script>
    $(function(){
        {% if request.user.is_authenticated %}

        $.ajax({
            url:'/info/',
            type:'get',
            success:function (data) {
                $('span.badge').text(data.count)
                if(data.count>0){
                    $("#yuan").show()
                }
            }
        })
        {% endif %}

        $('.avatar').click(function(event){
            event.stopPropagation();
            $('.meau').fadeIn()
        })
        $(document).click(function(){
            $(".meau").fadeOut();
            });
        $(window).scroll(function(){
                if ($(window).scrollTop()>100){
                    $("#toTop").fadeIn(1500);
                }
                else
                {
                    $("#toTop").fadeOut(1000);
                }
        });
            //当点击跳转链接后，回到页面顶部位置
            $("#toTop").click(function(){
                $('body,html').animate({scrollTop:0},500);
                return false;
            });
        //底部栏位置始终在最底部
        //console.log(window.screen.availHeight)
        $("body").css({
            "min-height": $(window).height()
        })
    })
</script>
{% block js %}
{% endblock %}
</body>
</html>

templates/pc/message.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
</head>
<body>
<p>{{ message|safe }}</p>
</body>
</html>