apps/article/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
from django.conf.urls import url
from django.urls import path, include
app_name='article'
from . import views
urlpatterns = [

  path('created/',views.Article_Add,name='created'),

  path('',views.ArticleList,name='index'),
  path('me/',views.ArticleMe,name='me'),
  path('blog_img_upload/',views.blog_img_upload,name='blog_img_upload'),
  path('detail/<uuid:article_id>',views.Article_detail,name='detail'),
  path('update/<uuid:article_id>',views.ArticleUpdate,name='update'),
  path('update_image/<uuid:article_id>',views.RemoveImage,name='update_image'),
  path('delete/',views.ArticleDelete,name='delete'),
  path('api/',views.api,name='api'),
  path('apis/',views.addModel),

]

apps/forum/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.urls import path, include
app_name='forum'
from . import views

urlpatterns = [
  #path('',views.login_view,name='index'),
  path('',views.index,name='forum'),
  path('add/',views.add_forum,name='add'),
  path('detail/<uuid:forum_id>/',views.forum_detail,name='detail'),
  path('cagetory/<int:category>/',views.forum_category,name='id'),
  path('del/<uuid:id>/',views.delForum,name='del'),
  ]

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from rest_framework.documentation import include_docs_urls

from rest_framework_jwt.views import obtain_jwt_token

from apps.article.views import ArticleCreated
from apps.course.views import CoursesList, CourseCreatedList, CourseListCreated, MeCoursesList
from apps.forum.views import Forum_plateView, ForumView, CommentView, Parent_CommentView
from apps.support.views import LinkList, EmailsList, BannerList, QQList, SeoList
from apps.user.views import test, captcha_refresh, yan, login_view, UserGetInfo, UserGetAllInfo, \
    PersonOthers, Register, active_user, get_message, UserMessages, qq, getClback, getClbackQQ
from django.views.generic import TemplateView

from website import settings
from apps.article import views
from apps.user.views import logout_view, Person, PersonApi,to_login
from rest_framework import routers

router = routers.DefaultRouter()
router.register('article_list', views.ArticleListView)
router.register('me_article_list', views.MeArticleListView)
router.register('ArticleCommit', views.ArticleCommit)
router.register('follow_list', views.FollowListView)
router.register('category', views.CategoryView)
router.register('article_Comment', views.ArticleCommintView)
router.register('comment_reply', views.ArticleCommentReplyView)
router.register('PersonApi', PersonApi)
router.register('apiinfo', UserGetInfo)
router.register('all_info', UserGetAllInfo)
# router.register('user_disbale', UserDisbale)
router.register('PersonOthers', PersonOthers)
router.register('UserMessages', UserMessages, base_name='UserMessages')
router.register('article', ArticleCreated)
router.register('courseList', CoursesList)
router.register('mecourseList', MeCoursesList)
router.register('course', CourseCreatedList)
router.register('Addtutorial', CourseListCreated)
router.register('BannerList', BannerList)
router.register('EmailsList', EmailsList)
router.register('LinkList', LinkList)
router.register('forum/category', Forum_plateView)
router.register('forum', ForumView)
router.register('CommentView', CommentView)
router.register('Parent_CommentView', Parent_CommentView)
router.register('get-list',QQList)
router.register('seo-list',SeoList,basename='seo-list')

urlpatterns = [

    #path('admins/', admin.site.urls),
    path('admin/', TemplateView.as_view(template_name='admin/index.html')),
   # path('404/', TemplateView.as_view(template_name='500.html')),
    # path('',test), # 这是生成验证码的图片
    url(r'^captcha/', include('captcha.urls')),
    path('refresh/', captcha_refresh),  # 这是生成验证码的图片
    path('yan/', yan),  # 这是生成验证码的图片
    path('', views.Home, name='home'),
    path('54', views.test, name='54'),
    path('login/', login_view, name='index'),
    path('info/', get_message, name='info'),
    path('person/', include('apps.user.urls')),
    path('logou/', logout_view, name='logou'),
    path('register/', Register.as_view(), name='register'),
    path('article/', include('apps.article.urls')),
    path('course/', include('apps.course.urls')),
    path('support/', include('apps.support.urls')),
    path('forum/', include('apps.forum.urls')),
    path('ads.txt/',TemplateView.as_view(template_name='ads.txt')),
    #url(r'^activate/(?P<token>\w+.[-_\w]*\w+.[-_\w]*\w+)/$', active_user, name='active_user'),
    path('activate/<str:token>', active_user, name='active_user'),
    url(r'^search/', include('haystack.urls'), name='haystack_search'),

    re_path(r'^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("api-docs/", include_docs_urls("API文档")),
    re_path(r'api/login/$', obtain_jwt_token),  # jwt认证
    url('auth-qq', to_login, name='qq-login'),
    url('qq', qq, name='qq'),
    url('callbackget', getClback, name='callbackget'),
    url('getClbackQQ', getClbackQQ, name='getClbackQQ'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})  # 配置文件上传html显示
]

#全局404
handler404='apps.user.views.page_not_found'
handler500='apps.user.views.page_error'

templates/search/search.html
{% extends 'pc/base.html' %}
{% load highlight %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
<style>
    span.highlighted { color: red; }
.list li{
    padding: 15px 0;
    border-bottom: 1px  solid #eee;
}
.forun-title{
    font-size: 16px;

}
.forun-title a{
    overflow:hidden;

text-overflow:ellipsis;

display:-webkit-box;

-webkit-box-orient:vertical;

-webkit-line-clamp:2;
    height: 42px;
}
.forun-info{
    color: #999;    margin-top: 8px;

}
.forun-num{
    position: absolute;
    right: 15px;
    bottom: 0;
    color: #999;
}
.f-name{
    font-size: 16px;
    padding: 15px;
    border-bottom: 1px solid #eee;
}
.f-name>.active{
    font-weight: bold;
}
.f-name>span{
    margin-right: 24px;
}
.list-text{
    padding-left: 15px;
    width:785px;
    position: relative;
}
#plate{
        padding: 15px 15px 0 15px;
    margin-bottom: 15px;
    background: #fff;
}
.forun-num>div{
    margin-left:12px
}
img.user{
    width: 48px;
    height: 48px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
}
</style>
{% endblock %}

{% block content %}
     <section class="main clearfix" style="display: flex">
     <article>
    {% if query %}

        {% for result in page.object_list %}
            <div class="blogs">
                {% if result.model_name == 'article' %}
                 <div class="blogs_cont">
                    <h3 style="overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    "><span class="blogs_type">{{ result.object.category.name }} </span>    <a style="overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    vertical-align: sub;" href="{% url 'article:detail' result.object.id %}">{% highlight result.object.title with query %}</a></h3>
                    <div class="blogs_foot clearfix">
                        <ul class="clearfix">
                            <li style="margin-bottom: 10px; max-height: 60px;height: auto;">
                                <a style="overflow: hidden;
    text-overflow: ellipsis;
    -webkit-box-orient: vertical;
    display: -webkit-box;
    -webkit-line-clamp: 3;" href="{% url 'article:detail' result.object.id %}" > {% highlight result.object.desc with query %}</a>
                            </li>
                            <li class="fl">
                                 <a href="{% url 'article:detail' result.object.id %}" class="clearfix">
                                     <span class="fl img_cover blogs_avatar" style="background: url({% if result.object.authors.user_imag %}
                                     {{ MEDIA_URL }}{{ result.object.authors.user_imag }}
                                         {% else %}
                                         {{ result.object.authors.user_image }}
                                     {% endif %})no-repeat;background-color: #ccc;"></span>
                                     <span class="fl blogs_name">{{ result.object.authors.username }}</span>
                                 </a>
                             </li>
                            <li class="fl blogs_time">发布于:{{ result.object.add_time }}</li>
                            <li class="fl blogs_view" style="background: url({% static 'img/eye.png' %})no-repeat 0 50%;">{{ result.object.click_nums }}</li>
                            <li class="fl blogs_comment" style="background: url({% static 'img/comment.png' %})no-repeat 0 50%;">{{ result.object.get_number }}</li>
                        </ul>
                    </div>

                </div>
                    {% elif result.model_name == 'forum' %}
                        <ul class="list">
                        <li class="clearfix">
                        <img src="{% if result.object.authors.user_imag %}
                    {{ MEDIA_URL }}{{ result.object.authors.user_imag }}
                    {% elif result.object.authors.user_image %}
                        {{ result.object.authors.user_image }}
                        {% else %}
                        {% static 'img/pc-icon.png' %}
                    {% endif %}" class="user fl" title="{{ result.object.authors.username }}"width="40px">
                    <div class="list-text fl">
                        <div class="fl">
                                 <p class="forun-title"><a href="{% url 'forum:detail' result.object.id %}"> {% highlight result.object.title with query%}</a></p>
                        <p class="forun-info">来自于 {{ result.object.category.name }}  {{ result.object.add_time }} </p>
                        </div>

                           <div class="fr flex forun-num">
                        <div>评论{{ result.object.get_number }}</div>
                        <div>浏览 {{ result.object.click_nums}}</div>
                    </div>
                    </div>

                    </li>

                        </ul>
                {% endif %}

            </div>



        {% empty %}
            <div class="no-post" style="margin-top: 15px;">没有搜索到你想要的结果！</div>
        {% endfor %}
        {% if page.has_previous or page.has_next %}
             <div class="pageturn">
           <ul class="pagination">
                {% if page.has_previous %}
                   <li> <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">上一页</a></li>
                {% else %}
                      <li><span class="disabled next btn" disabled=""> 上一页</span></li>
              {% endif %}


                {% if page.has_next %}
                    <li><a href="?q={{ query }}&amp;page={{ page.next_page_number }}">下一页</a></li>

                {% else %}
                     <li><span class="disabled next btn" disabled=""> 下一页</span></li>
              {% endif %}
           </ul>
             </div>

        {% endif %}
    {% else %}
        请输入搜索关键词，例如 django
    {% endif %}
           </article>
     <aside class="fr">




<div class="sidebar">
</div>


    </aside>

       </section>
{% endblock content %}